version: '3.9'

services:
  ahoi-burger-backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://ahoi-burger-db:5432/burger
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      API_KEY: "ahoi-burger-secret"
    depends_on:
      - ahoi-burger-db

  ahoi-burger-db:
    image: postgres:17.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: burger
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: