spring:
  application:
    name: ahoiburger
  datasource:
    url: jdbc:postgresql://localhost:5434/burger
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

application:
  api-key: "ahoi-burger-secret"

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui