spring:
  application:
    name: ahoiburger
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/burger}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

application:
  api-key: ${API_KEY:ahoi-burger-secret}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
